<?php if($user = $this->identity()): ?>
<div class="contact-box">
    <div class="col-sm-4">
        <div class="text-center">
            <img alt="image" class="m-t-xs img-responsive" src="<?php echo $this->basePath('/img/uzik-black.png') ?>">
        </div>
    </div>
    <div class="col-sm-8">
        <h3><strong><?php echo $this->escapeHtml($user->getName()) ?></strong></h3>
        <p><i class="fa fa-envelope"></i> <?php echo $this->escapeHtml($user->getMail()) ?></p>
        <p><i class="fa fa-at"></i> <?php echo $this->escapeHtml($user->getLogin()) ?></p>
		<a href="<?php echo $this->url('admin/default', array('action' => 'edit', 'controller' => 'user')) ?>" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit') ?></a>
    </div>
    <div class="clearfix"></div>
</div>

<?php endif; ?>