<p><a href="<?php echo $this->url('admin/default', array('action' => 'add', 'controller' => 'roles')) ?>" class="btn btn-white btn-sm"><i class="fa fa-plus"></i> <?php echo $this->translate('Add') ?></a></p>

<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5><?php echo $this->translate('Roles') ?></h5>
    </div>
    <div class="ibox-content">
		<table class="table table-striped table-bordered table-hover data-table" >
		    <thead>
			    <tr>
			        <th class="sort search"><?php echo $this->translate('ID') ?></th>
			        <th class="sort search"><?php echo $this->translate('Label') ?></th>
			        <th class="sort search"><?php echo $this->translate('Name') ?></th>
			        <th><?php echo $this->translate('Status') ?></th>
			        <th><?php echo $this->translate('Actions') ?></th>
			    </tr>
		    </thead>
		    <tbody>
		    	<?php foreach($this->roles as $role): ?>
			    <tr>
			        <td><?php echo $role->getId() ?></td>
			        <td><?php echo $role->getLabel() ?></td>
			        <td><?php echo $role->getName() ?></td>
			        <td class="center"><i class="fa <?php echo $role->getStatus() == 1 ? 'fa-unlock active' : 'fa-lock inactive' ?>"></td>
			        <td>
			        	<a href="<?php echo $this->url('admin/default', array('action' => 'edit', 'controller' => 'roles'), array('query' => array('id' => $role->getId()))) ?>" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit') ?></a>
			        </td>
			    </tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>