<?php
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
?>

<?php foreach ($container as $page): ?>
    <?php if (!$this->navigation()->accept($page)) continue; ?>
    <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
    <?php
    $hasChildren = $page->hasPages();
    //check if access is allowed at least one item
    $access = false;
    foreach ($page->getPages() as $child) {
        if ($this->navigation()->accept($child)) {
            $access = true;
        }
    }
    if ($access || !$hasChildren) :
        ?>
        <li<?php if ($page->isActive(true)) echo ' class="active"' ?>>
            <a
            	href="<?php echo $page->getHref() ?>"
            	<?php if ($page->getTarget() != ""): ?>
                    target="<?php echo $page->getTarget(); ?>"
                <?php endif; ?>
            >
                <?php if ($page->get("icon") !== ""): ?>
                    <i class="<?php echo $page->get("icon"); ?>"></i>
                <?php endif; ?>
                <span class="nav-label"><?php echo $page->getLabel() ?></span>
                <?php if( $hasChildren): ?>
                <span class="fa arrow"></span>
                <?php endif; ?>
            </a>
            <?php if ($hasChildren): ?>
            <ul class="nav nav-second-level">
                <?php foreach ($page->getPages() as $child): ?>
                    <?php if (!$this->navigation()->accept($child)) continue; ?>
                    <li<?php if ($child->isActive()) echo ' class="active"' ?>>
                        <a 
                            href="<?php echo $child->getHref() ?>"
                            <?php if ($child->getTarget() != ""): ?>
                                target="<?php echo $child->getTarget(); ?>"
                            <?php endif; ?> 
                        >
                            <?php echo $child->getLabel() ?>
                        </a>
                    </li>
                <?php endforeach ?>
            </ul>
            <?php endif ?>
        </li>   
    <?php endif; ?>
<?php endforeach ?>