<h1><?php echo $this->translate('404') ?></h1>
<h3 class="font-bold"><?php echo $this->translate('Page Not Found') ?></h3>

<div class="error-desc">
    <?php echo $this->translate('Sorry, but the page you are looking for has note been found. Try checking the URL for error, then hit the refresh button on your browser or try found something else in our app.') ?>
    <br>
    <a href="javascript: history.go(-1)" class="btn btn-white m-t"><?php echo $this->translate('Back to previous page') ?></a>
</div>