<?php 

$form = $this->form;
$form->prepare();

?>

<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->adminFormRow($form->get('name')) ?>
    <?php echo $this->adminFormRow($form->get('mail')) ?>
    <?php echo $this->adminFormRow($form->get('login')) ?>
    <?php echo $this->adminFormRow($form->get('password')) ?>
    <?php echo $this->adminFormRow($form->get('password2')) ?>
    <?php echo $this->adminFormRow($form->get('super_admin'), 'append') ?>
    <?php echo $this->adminFormRow($form->get('roles'), 'prepend') ?>
    <?php echo $this->adminFormRow($form->get('status'), 'append') ?>
	<?php echo $this->formSubmit($form->get('submit')) ?>
<?php echo $this->form()->closeTag(); ?>