<?php 

$elements = $this->form->getElements();
$form = $this->form;
$form->prepare();

?>

<?php echo $this->form()->openTag($form); ?>

	<?php if(isset($elements['title']))
		echo $this->adminFormRow($form->get('title')) ?>

    <?php if(isset($elements['status']))
    	echo $this->adminFormRow($form->get('status'), 'append') ?>

    <?php if(isset($elements['status_translation']))
    	echo $this->adminFormRow($form->get('status_translation'), 'append') ?>
    	
	<?php echo $this->formSubmit($form->get('submit')) ?>
<?php echo $this->form()->closeTag(); ?>