<?php if(count($this->territories) == 1): ?>
<p>
	<?php foreach($this->locales as $territoryLocales): ?>
	<div class="btn-group">
		<button data-toggle="dropdown" class="btn btn-white btn-sm dropdown-toggle"><i class="fa fa-plus"></i> <?php echo $this->translate('Add') ?> <span class="caret"></span></button>
		<ul class="dropdown-menu">
			<?php foreach($territoryLocales as $locale => $label): ?>
            <li><a href="<?php echo $this->url('admin/default', array('action' => 'add', 'controller' => 'news'), array('query' => array('locale' => $locale, 'id_territory' => $this->territories[0]->getId()))) ?>"><?php echo $label ?></a></li>
        	<?php endforeach; ?>
        </ul>
	</div>
	<?php endforeach; ?>
</p>
<?php endif; ?>

<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5><?php echo $this->translate('News') ?></h5>
    </div>
    <div class="ibox-content">

		<?php if(count($this->territories) > 1): ?>
		<div class="panel blank-panel">
		    <div class="panel-heading">
		        <div class="panel-options">
		            <ul class="nav nav-tabs">
		            	<?php foreach($this->territories as $index => $territory): ?>
		                <li<?php if($index == 0) echo ' class="active"' ?>><a data-toggle="tab" href="#tab-<?php echo $index ?>"><?php echo $territory->getName() ?></a></li>
		            	<?php endforeach; ?>
		            </ul>
		        </div>
		    </div>
		    <div class="panel-body">
		        <div class="tab-content">

		<?php endif; ?>

		<?php foreach($this->territories as $index => $territory): ?>

		            <?php if(count($this->territories) > 1): ?><div id="tab-<?php echo $index ?>" class="tab-pane<?php if($index == 0) echo ' active' ?>"><?php endif; ?>

						<?php if(count($this->territories) > 1): ?>
						<p>
							<div class="btn-group">
								<button data-toggle="dropdown" class="btn btn-white btn-sm dropdown-toggle"><i class="fa fa-plus"></i> <?php echo $this->translate('Add') ?> <span class="caret"></span></button>
								<ul class="dropdown-menu">
									<?php foreach($locales[$territory->getId()] as $locale => $label): ?>
						            <li><a href="<?php echo $this->url('admin/default', array('action' => 'add', 'controller' => 'news'), array('query' => array('locale' => $locale, 'id_territory' => $territory->getId()))) ?>"><?php echo $label ?></a></li>
						        	<?php endforeach; ?>
						        </ul>
							</div>
						</p>
						<?php endif; ?>

		                <table class="table table-striped table-bordered table-hover data-table" >
						    <thead>
							    <tr>
							        <th class="sort search"><?php echo $this->translate('ID') ?></th>
							        <th class="sort search"><?php echo $this->translate('Title') ?></th>
							        <th><?php echo $this->translate('Status') ?></th>
							        <th><?php echo $this->translate('Actions') ?></th>
							    </tr>
						    </thead>
						    <tbody>
						    	<?php foreach($this->news[$territory->getId()] as $news): ?>
							    <tr>
							        <td><?php echo $news->getId() ?></td>
							        <td><?php echo $news->getTitle() ?></td>
							        <td class="center"><i class="fa <?php echo $news->getStatus() == 1 ? 'fa-unlock active' : 'fa-lock inactive' ?>"></td>
							        <td>
							        	<a href="<?php echo $this->url('admin/default', array('action' => 'edit', 'controller' => 'news'), array('query' => array('id' => $news->getId(), 'id_territory' => $territory->getId()))) ?>" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit') ?></a>
							        	<a href="<?php echo $this->url('admin/default', array('action' => 'translations', 'controller' => 'news'), array('query' => array('id' => $news->getId(), 'id_territory' => $territory->getId()))) ?>" class="btn btn-white btn-sm"><i class="fa fa-language"></i> <?php echo $this->translate('Translations') ?></a>
							        </td>
							    </tr>
								<?php endforeach; ?>
							</tbody>
						</table>

		            <?php if(count($this->territories) > 1): ?></div><?php endif; ?>
		<?php endforeach; ?>
		
		<?php if(count($this->territories) > 1): ?>
		        </div>
		    </div>
		</div>
		<?php endif; ?>
	</div>
</div>