<?php if(!empty($this->unused_locales)): ?>
<p>
	<div class="btn-group">
		<button data-toggle="dropdown" class="btn btn-white btn-sm dropdown-toggle"><i class="fa fa-plus"></i> <?php echo $this->translate('Add') ?> <span class="caret"></span></button>
		<ul class="dropdown-menu">
			<?php foreach($this->unused_locales as $locale => $label): ?>
            <li><a href="<?php echo $this->url('admin/default', array('action' => 'add-translation', 'controller' => 'news'), array('query' => array('id' => $this->entity->getId(), 'locale' => $locale, 'id_territory' => $this->territory->getId()))) ?>"><?php echo $label ?></a></li>
        	<?php endforeach; ?>
        </ul>
	</div>
</p>
<?php endif; ?>

<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5><?php echo $this->translate('Translations for ') ?> #<?php echo $this->entity->getId() ?> : "<?php echo $this->entity->getTitle() ?>"</h5>
    </div>
    <div class="ibox-content">
		<table class="table table-striped table-bordered table-hover data-table" >
		    <thead>
			    <tr>
			        <th class="sort search"><?php echo $this->translate('Title') ?></th>
			        <th class="sort search"><?php echo $this->translate('Locale') ?></th>
			        <th><?php echo $this->translate('Status') ?></th>
			        <th><?php echo $this->translate('Actions') ?></th>
			    </tr>
		    </thead>
		    <tbody>
		    	<?php foreach($this->translations as $locale => $translation): ?>
			    <tr>
			        <td><?php echo $translation['title'] ?></td>
			        <td><?php echo $this->locales[$locale] ?></td>
			        <td class="center"><i class="fa <?php echo $translation['status_translation'] == 1 ? 'fa-unlock active' : 'fa-lock inactive' ?>"></td>
			        <td>
			        	<a href="<?php echo $this->url('admin/default', array('action' => 'edit-translation', 'controller' => 'news'), array('query' => array('id' => $this->entity->getId(), 'locale' => $locale, 'id_territory' => $this->territory->getId()))) ?>" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit') ?></a>
			        </td>
			    </tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>