 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My artists';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('artist', array('action'=>'add'));?>">Add new artist</a>
 </p>

 <table class="table">
 <tr>
     <th>Nom</th>
     <th>Description</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($artists as $artist) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($artist->name);?></td>
     <td><?php echo $this->escapeHtml($artist->description);?></td>
     <td>
         <a href="<?php echo $this->url('artist',
             array('action'=>'edit', 'id' => $artist->id));?>">Edit</a>
         <a href="<?php echo $this->url('artist',
             array('action'=>'delete', 'id' => $artist->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>