<p><a href="<?php echo $this->url('admin/default', array('action' => 'add', 'controller' => 'territories')) ?>" class="btn btn-white btn-sm"><i class="fa fa-plus"></i> <?php echo $this->translate('Add') ?></a></p>

<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5><?php echo $this->translate('Territories') ?></h5>
    </div>
    <div class="ibox-content">
		<table class="table table-striped table-bordered table-hover data-table" >
		    <thead>
			    <tr>
			        <th class="sort search"><?php echo $this->translate('ID') ?></th>
			        <th class="sort search"><?php echo $this->translate('Name') ?></th>
			        <th class="sort search"><?php echo $this->translate('Url code') ?></th>
			        <th class="sort search"><?php echo $this->translate('Langs') ?></th>
			        <th class="sort"><?php echo $this->translate('Default lang') ?></th>
			        <th><?php echo $this->translate('Status') ?></th>
			        <th><?php echo $this->translate('Actions') ?></th>
			    </tr>
		    </thead>
		    <tbody>
		    	<?php foreach($this->territories as $territory): ?>
			    <tr>
			        <td><?php echo $territory->getId() ?></td>
			        <td><?php echo $territory->getName() ?></td>
			        <td><?php echo $territory->getUrlCode() ?></td>
			        <td><?php foreach(\Zend\Json\Json::decode($territory->getLangs()) as $_lang):
			        	echo $this->langs[$_lang] . '<br>';
			        endforeach;?></td>
			        <td><?php echo $this->langs[$territory->getDefaultLang()] ?></td>
			        <td class="center"><i class="fa <?php echo $territory->getStatus() == 1 ? 'fa-unlock active' : 'fa-lock inactive' ?>"></td>
			        <td>
			        	<a href="<?php echo $this->url('admin/default', array('action' => 'edit', 'controller' => 'territories'), array('query' => array('id' => $territory->getId()))) ?>" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit') ?></a>
			        </td>
			    </tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>