<div class="content-wrapper">
<div id="content">
<div class="container">
<?php foreach($posts as $post):?>
	<div class="element clearfix rectangle col1-1 home teaser" style="height: 403.2px;">


		<div class="padding-wrapper">
		<a href="<?= $post["link"]?>" title="">
			<figure class="images">
			<?php if(is_array($post['source'])):
						echo '<img class="attachment-full size-full wp-post-image" alt="image05[1]" src="'.$post["source"]["medium"].'"  sizes="(max-width: 600px) 100vw, 600px" width="600" height="400" /><br>';
					elseif(!empty($post['source'])):
						echo '<iframe width="420" height="315" src="'.str_replace("https://youtu.be/", "https://www.youtube.com/embed/", $post["source"]).'"></iframe><br>';
					endif;
					?>
			</figure>
		</a>

		<div class="grey-bg">
			<p class="small categories"><a href="http://themes.fastwp.net/cc/index.php/category/food/" rel="category tag"><?= strtoupper($post["type"])?></a></p>
			<p><?= $post["message"]?></p>

			<div class="stats">
				<p class="lefted">Le <?= date("d/m/Y",$post["date"])?><span class="alignright">
				<span class="padding"><a href="#" class="zilla-likes" id="zilla-likes-60" title="Like this"><span class="zilla-likes-count"><i class="fa fa-heart"></i> 25</span> <span class="zilla-likes-postfix"></span></a></span>            <a href="#" title=""><i class="fa fa-comments"></i>0</a>
				</span>
				</p>
			</div>
		</div>
		</div>


	</div>
<?php endforeach;?>

</div>
		</div>
		</div>